if: tag IS blank

sudo: false
git:
  depth: 1

matrix:
  fast_finish: true

cache: yarn

language: node_js
node_js:
  - "node"
  - "lts/*"
env:
  - COMPONENT=@emmanuelgautier/lerna-example-hapi
  - COMPONENT=@emmanuelgautier/lerna-example-react-app
  - COMPONENT=@emmanuelgautier/lerna-example-validators
stages:
  - test
  - build
  - name: publish
    if: branch = master
script:
  - ./ci/test $COMPONENT
  - ./ci/build $COMPONENT
jobs:
  include:
    - script: ./ci/test $COMPONENT
    - stage: build
      script: ./ci/build $COMPONENT
    - stage: publish
      env:
        - COMPONENT=all
      script: ./ci/publish
    - stage: deploy
      script: skip
