if: tag IS blank

sudo: false
git:
  depth: 1

matrix:
  fast_finish: true

cache: yarn

language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: test
      node_js: "node"
      env: COMPONENT=@emmanuelgautier/lerna-example-express
      script: ./ci/test $COMPONENT
    - stage: test
      node_js: "lts/*"
      env: COMPONENT=@emmanuelgautier/lerna-example-express
      script: ./ci/test $COMPONENT
    - stage: test
      node_js: "node"
      env: COMPONENT=@emmanuelgautier/lerna-example-react-app
      script: ./ci/test $COMPONENT
    - stage: test
      node_js: "lts/*"
      env: COMPONENT=@emmanuelgautier/lerna-example-react-app
      script: ./ci/test $COMPONENT
    - stage: test
      node_js: "node"
      env: COMPONENT=@emmanuelgautier/lerna-example-validators
      script: ./ci/test $COMPONENT
    - stage: test
      node_js: "lts/*"
      env: COMPONENT=@emmanuelgautier/lerna-example-validators
      script: ./ci/test $COMPONENT
    - stage: build
      node_js: "node"
      env: COMPONENT=@emmanuelgautier/lerna-example-express
      script: ./ci/build $COMPONENT
    - stage: build
      node_js: "lts/*"
      env: COMPONENT=@emmanuelgautier/lerna-example-express
      script: ./ci/build $COMPONENT
    - stage: build
      node_js: "node"
      env: COMPONENT=@emmanuelgautier/lerna-example-react-app
      script: ./ci/build $COMPONENT
    - stage: build
      node_js: "lts/*"
      env: COMPONENT=@emmanuelgautier/lerna-example-react-app
      script: ./ci/build $COMPONENT
    - stage: build
      node_js: "node"
      env: COMPONENT=@emmanuelgautier/lerna-example-validators
      script: ./ci/build $COMPONENT
    - stage: build
      node_js: "lts/*"
      env: COMPONENT=@emmanuelgautier/lerna-example-validators
      script: ./ci/build $COMPONENT
    - stage: publish
      script: ./ci/publish

stages:
  - test
  - build
  - name: publish
    if: branch = master
