sudo: false
language: node_js

if: tag IS blank

git:
  depth: 1

cache: yarn

before_script:
  - chmod 777 test.sh
  - chmod 777 build.sh

node_js:
  - "node"
  - "lts/*"

env:
  - COMPONENT=@emmanuelgautier/lerna-example-hapi
  - COMPONENT=@emmanuelgautier/lerna-example-react-app
  - COMPONENT=@emmanuelgautier/lerna-example-validators


script:
  - ./test.sh
  - ./build.sh

stages:
  - test
  - publish
  - deploy

jobs:
  include:
    - stage: publish
      env:
        - COMPONENT=all
      script: yarn publish
    - stage: deploy
      script: skip
      env: none

notifications:
  email:
    on_failure: never
